### PR TITLE
Upgrade @shopify/cli, clean pnpm

### PR DESCRIPTION
**Pull request by cyrilchapon**
- I upgraded @shopify/cli to the latest version (I had bugs on ngrok tunnel, this fixed it)
- I removed `pnpm-lock.json`s and gitignored them, [according to shopify default strategy in base repo](https://github.com/KaiSpencer/shopify-app-template-node-ts/blob/main/.gitignore#L30-L34)

### CODE REVIEW

**Comment by KaiSpencer** [comment]
LGTM Thank you 😃

**Review by KaiSpencer — APPROVED** [review]

**Comment by KaiSpencer** [comment]
@all-contributors
please add @KaiSpencer for code. 
please add @cyrilchapon  for code.

**Comment by KaiSpencer** [comment]
@all-contributors please add @cyrilchapon for code

**Comment by KaiSpencer** [comment]
@all-contributors please add @cyrilchapon for code

**Comment by cyrilchapon** [comment]
@KaiSpencer , thanks for this merge.

I'm getting a strange install loop when installing the app.
Can you reproduce ? Any idea ?

**Comment by KaiSpencer** [comment]
Hi @cyrilchapon,

Which package manager?
I just installed fine with
pnpm: 7.18.2
node: v16.15.1

I also tested and was all working for me before I merged

**Comment by cyrilchapon** [comment]
Ok. Nah I think it was some token or cookie issue within shopify itself.
Pretty strange.

Unlogged from everything, remove caches from ngrok and yarn; worked back.

**Comment by cyrilchapon** [comment]
@KaiSpencer, see https://github.com/Shopify/shopify-app-template-node/issues/1215

This was related to trailing .sqllite

**Pull request merged**
